# Generated by Django 4.2.4 on 2024-04-25 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='user_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='first_name',
        ),
    ]
